version: 2
jobs:
  build_node_10:
    docker:
    - image: circleci/node:10.0.0
    working_directory: ~/adonis-framework
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: npm test

  build_node_latest:
    docker:
    - image: circleci/node:11.10.0
    working_directory: ~/adonis-framework
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: npm test
workflows:
  version: 2
  workflow:
    jobs:
    - build_node_latest
    - build_node_10
